import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Providers from "@/components/Providers";
import { Lora } from "next/font/google";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const lora = Lora({ subsets: ["latin"] });
console.log(lora.className);

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`bg-slate-100 dark:bg-black text-black dark:text-white ${lora.className}`}>
                <Providers>
                    <Navbar />
                    {children}
                </Providers>
            </body>
        </html>
    );
}
